// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.Readings.CategoryList = function() {
    var cat, labelname, list, _ref;
    list = $(this);
    list.empty();
    _ref = Readings.config.get('categories');
    for (cat in _ref) {
      labelname = _ref[cat];
      list.append("<li><a href=\"tags.html?category=" + cat + "\" data-category=\"" + cat + "\">" + labelname + "</a></li>");
    }
    console.log("category list updte");
    return list.listview('refresh');
  };

}).call(this);
