// Generated by CoffeeScript 1.3.3
(function() {
  var url_to_slug;

  url_to_slug = function(url) {
    var slug_in_url;
    slug_in_url = /([a-z0-9-]+)[/]?$/;
    return slug_in_url.exec(url)[1];
  };

  Readings.Book = (function() {

    function Book(record) {
      $.extend(this, record);
    }

    Book.prototype.render = function() {
      var wlurl;
      wlurl = Readings.config.get('wlurl');
      return "<li>      <a href=\"reader.html?book_id=" + this.id + "\">        <img src=\"" + wlurl + this.cover + "\">        <h3> " + this.title + "</h3>       </a>     </li>";
    };

    Book.prototype.group = function() {
      return this.authors;
    };

    return Book;

  })();

  Readings.Tag = (function() {

    function Tag(record, category) {
      this.category = category;
      $.extend(this, record);
    }

    Tag.prototype.render = function() {
      return "<li><a href=\"books.html?tag_id=" + this.id + "\">" + this.name + "</a></li>";
    };

    Tag.prototype.group = function() {
      return this.sort_key[0].toUpperCase();
    };

    return Tag;

  })();

}).call(this);
