// Generated by CoffeeScript 1.3.3
(function() {

  Readings.Tag = (function() {

    function Tag(record) {
      this.href = record.href;
      this.name = record.name;
      this.slug = $.grep(this.href.split('/'), function(e) {
        return e !== "";
      });
    }

    Tag.prototype.render = function() {
      return "<li><a href=\"#\">" + this.name + "</a></li>";
    };

    return Tag;

  })();

  $.fn.Readings.TagList = function(category) {
    return this.each(function() {
      var list;
      $('[data-role=header] h1').text(Readings.config.get('categories')[category]);
      list = $('[data-role=listview]', this);
      return $.ajax({
        url: Readings.config.get('wlurl') + ("/api/" + category),
        contentType: "json",
        success: function(data) {
          var t, tags, _i, _len;
          console.log(data);
          tags = $.map(data, function(rec) {
            return new Readings.Tag(rec);
          });
          list.empty();
          for (_i = 0, _len = tags.length; _i < _len; _i++) {
            t = tags[_i];
            list.append(t.render());
          }
          return list.listview('refresh');
        }
      });
    });
  };

}).call(this);
